# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.mahnstufe_api import MahnstufeApi  # noqa: E501
from swagger_client.rest import ApiException


class TestMahnstufeApi(unittest.TestCase):
    """MahnstufeApi unit test stubs"""

    def setUp(self):
        self.api = MahnstufeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_mahnstufe_mahnstufe_post(self):
        """Test case for add_mahnstufe_mahnstufe_post

        Add Mahnstufe  # noqa: E501
        """
        pass

    def test_get_mahnstufe_mahnstufe_get(self):
        """Test case for get_mahnstufe_mahnstufe_get

        Get Mahnstufe  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
