# coding: utf-8

"""
    sync-service-api-gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sync_service_api_gateway.api.portal_bp_update_api import PortalBPUpdateApi


class TestPortalBPUpdateApi(unittest.TestCase):
    """PortalBPUpdateApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PortalBPUpdateApi()

    def tearDown(self) -> None:
        pass

    def test_portal__bp_update_add_portal_bp_update(self) -> None:
        """Test case for portal__bp_update_add_portal_bp_update

        Add Portal Bp Update
        """
        pass

    def test_portal__bp_update_find_portal_bp_update_by_state(self) -> None:
        """Test case for portal__bp_update_find_portal_bp_update_by_state

        Find Portal Bp Update By State
        """
        pass

    def test_portal__bp_update_get_portal_bp_update(self) -> None:
        """Test case for portal__bp_update_get_portal_bp_update

        Get Portal Bp Update
        """
        pass

    def test_portal__bp_update_get_portal_bp_update_by_id(self) -> None:
        """Test case for portal__bp_update_get_portal_bp_update_by_id

        Get Portal Bp Update By Id
        """
        pass

    def test_portal__bp_update_increment_portal_bp_update_retry(self) -> None:
        """Test case for portal__bp_update_increment_portal_bp_update_retry

        Increment Portal Bp Update Retry
        """
        pass

    def test_portal__bp_update_update_portal_bp_update_state(self) -> None:
        """Test case for portal__bp_update_update_portal_bp_update_state

        Update Portal Bp Update State
        """
        pass


if __name__ == '__main__':
    unittest.main()
