# coding: utf-8

"""
    sync-service-api-gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sync_service_api_gateway.api.portal_bpiban_mail_api import PortalBPIBANMailApi


class TestPortalBPIBANMailApi(unittest.TestCase):
    """PortalBPIBANMailApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PortalBPIBANMailApi()

    def tearDown(self) -> None:
        pass

    def test_portal__bp_iban_mail_add_portal_bp_iban_mail(self) -> None:
        """Test case for portal__bp_iban_mail_add_portal_bp_iban_mail

        Add Portal Bp Iban Mail
        """
        pass

    def test_portal__bp_iban_mail_find_portal_bp_iban_mail_by_state(self) -> None:
        """Test case for portal__bp_iban_mail_find_portal_bp_iban_mail_by_state

        Find Portal Bp Iban Mail By State
        """
        pass

    def test_portal__bp_iban_mail_get_portal_bp_iban_mail(self) -> None:
        """Test case for portal__bp_iban_mail_get_portal_bp_iban_mail

        Get Portal Bp Iban Mail
        """
        pass

    def test_portal__bp_iban_mail_get_portal_bp_iban_mail_by_id(self) -> None:
        """Test case for portal__bp_iban_mail_get_portal_bp_iban_mail_by_id

        Get Portal Bp Iban Mail By Id
        """
        pass

    def test_portal__bp_iban_mail_get_portal_bp_update_by_transaction_id(self) -> None:
        """Test case for portal__bp_iban_mail_get_portal_bp_update_by_transaction_id

        Get Portal Bp Update By Transaction Id
        """
        pass

    def test_portal__bp_iban_mail_update_portal_bp_iban_mail_retry_count(self) -> None:
        """Test case for portal__bp_iban_mail_update_portal_bp_iban_mail_retry_count

        Update Portal Bp Iban Mail Retry Count
        """
        pass

    def test_portal__bp_iban_mail_update_portal_bp_iban_mail_state(self) -> None:
        """Test case for portal__bp_iban_mail_update_portal_bp_iban_mail_state

        Update Portal Bp Iban Mail State
        """
        pass


if __name__ == '__main__':
    unittest.main()
