# coding: utf-8

"""
    sync-service-api-gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sync_service_api_gateway.models.ih_notification_update_jira_create_create import IHNotificationUpdateJiraCreateCreate

class TestIHNotificationUpdateJiraCreateCreate(unittest.TestCase):
    """IHNotificationUpdateJiraCreateCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IHNotificationUpdateJiraCreateCreate:
        """Test IHNotificationUpdateJiraCreateCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IHNotificationUpdateJiraCreateCreate`
        """
        model = IHNotificationUpdateJiraCreateCreate()
        if include_optional:
            return IHNotificationUpdateJiraCreateCreate(
                parent_transaction_id = '',
                jira_ticket_number = '',
                notif_number = 56
            )
        else:
            return IHNotificationUpdateJiraCreateCreate(
                parent_transaction_id = '',
                jira_ticket_number = '',
                notif_number = 56,
        )
        """

    def testIHNotificationUpdateJiraCreateCreate(self):
        """Test IHNotificationUpdateJiraCreateCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
