# coding: utf-8

"""
    sync-service-api-gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sync_service_api_gateway.api.ih_notification_create_api import IHNotificationCreateApi


class TestIHNotificationCreateApi(unittest.TestCase):
    """IHNotificationCreateApi unit test stubs"""

    def setUp(self) -> None:
        self.api = IHNotificationCreateApi()

    def tearDown(self) -> None:
        pass

    def test_i_h_notification__create_add_ih_notification_create(self) -> None:
        """Test case for i_h_notification__create_add_ih_notification_create

        Add Ih Notification Create
        """
        pass

    def test_i_h_notification__create_find_ih_notification_create_by_state(self) -> None:
        """Test case for i_h_notification__create_find_ih_notification_create_by_state

        Find Ih Notification Create By State
        """
        pass

    def test_i_h_notification__create_get_ih_notification_create(self) -> None:
        """Test case for i_h_notification__create_get_ih_notification_create

        Get Ih Notification Create
        """
        pass

    def test_i_h_notification__create_get_ih_notification_create_by_id(self) -> None:
        """Test case for i_h_notification__create_get_ih_notification_create_by_id

        Get Ih Notification Create By Id
        """
        pass

    def test_i_h_notification__create_increment_ih_notification_create_retry_count(self) -> None:
        """Test case for i_h_notification__create_increment_ih_notification_create_retry_count

        Increment Ih Notification Create Retry Count
        """
        pass

    def test_i_h_notification__create_update_ih_notification_create_state(self) -> None:
        """Test case for i_h_notification__create_update_ih_notification_create_state

        Update Ih Notification Create State
        """
        pass


if __name__ == '__main__':
    unittest.main()
