# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.portal_api import PortalApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPortalApi(unittest.TestCase):
    """PortalApi unit test stubs"""

    def setUp(self):
        self.api = PortalApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_portal_bp_update_portal_bp_update_post(self):
        """Test case for add_portal_bp_update_portal_bp_update_post

        Add Portal Bp Update  # noqa: E501
        """
        pass

    def test_get_portal_bp_update_portal_bp_update_get(self):
        """Test case for get_portal_bp_update_portal_bp_update_get

        Get Portal Bp Update  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
