# coding: utf-8

"""
    sync-service-api-gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sync_service_api_gateway.api.ih_notification_close_api import IHNotificationCloseApi


class TestIHNotificationCloseApi(unittest.TestCase):
    """IHNotificationCloseApi unit test stubs"""

    def setUp(self) -> None:
        self.api = IHNotificationCloseApi()

    def tearDown(self) -> None:
        pass

    def test_i_h_notification__close_add_ih_notification_close(self) -> None:
        """Test case for i_h_notification__close_add_ih_notification_close

        Add Ih Notification Close
        """
        pass

    def test_i_h_notification__close_find_ih_notification_close_by_state(self) -> None:
        """Test case for i_h_notification__close_find_ih_notification_close_by_state

        Find Ih Notification Close By State
        """
        pass

    def test_i_h_notification__close_get_ih_notification_close(self) -> None:
        """Test case for i_h_notification__close_get_ih_notification_close

        Get Ih Notification Close
        """
        pass

    def test_i_h_notification__close_get_ih_notification_close_by_id(self) -> None:
        """Test case for i_h_notification__close_get_ih_notification_close_by_id

        Get Ih Notification Close By Id
        """
        pass

    def test_i_h_notification__close_increment_ih_notification_close_retry_count(self) -> None:
        """Test case for i_h_notification__close_increment_ih_notification_close_retry_count

        Increment Ih Notification Close Retry Count
        """
        pass

    def test_i_h_notification__close_update_ih_notification_close_state(self) -> None:
        """Test case for i_h_notification__close_update_ih_notification_close_state

        Update Ih Notification Close State
        """
        pass


if __name__ == '__main__':
    unittest.main()
