# coding: utf-8

"""
    sync-service-api-gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sync_service_api_gateway.models.ih_notification_close import IHNotificationClose

class TestIHNotificationClose(unittest.TestCase):
    """IHNotificationClose unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IHNotificationClose:
        """Test IHNotificationClose
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IHNotificationClose`
        """
        model = IHNotificationClose()
        if include_optional:
            return IHNotificationClose(
                jira_ticket_number = '',
                notif_number = 56,
                transaction_id = '',
                state = 'initial',
                retry_count = 56,
                creation_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                last_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return IHNotificationClose(
                jira_ticket_number = '',
                notif_number = 56,
        )
        """

    def testIHNotificationClose(self):
        """Test IHNotificationClose"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
