# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.kontoauszug_api import KontoauszugApi  # noqa: E501
from swagger_client.rest import ApiException


class TestKontoauszugApi(unittest.TestCase):
    """KontoauszugApi unit test stubs"""

    def setUp(self):
        self.api = KontoauszugApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_kontoauszug_kontoauszug_post(self):
        """Test case for add_kontoauszug_kontoauszug_post

        Add Kontoauszug  # noqa: E501
        """
        pass

    def test_get_kontoauszug_kontoauszug_get(self):
        """Test case for get_kontoauszug_kontoauszug_get

        Get Kontoauszug  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
