# coding: utf-8

"""
    sync-service-api-gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sync_service_api_gateway.api.ih_notification_jira_update_create_api import IHNotificationJiraUpdateCreateApi


class TestIHNotificationJiraUpdateCreateApi(unittest.TestCase):
    """IHNotificationJiraUpdateCreateApi unit test stubs"""

    def setUp(self) -> None:
        self.api = IHNotificationJiraUpdateCreateApi()

    def tearDown(self) -> None:
        pass

    def test_i_h_notification__jira_update_create_add_ih_notification_update_jira_create(self) -> None:
        """Test case for i_h_notification__jira_update_create_add_ih_notification_update_jira_create

        Add Ih Notification Update Jira Create
        """
        pass

    def test_i_h_notification__jira_update_create_find_ih_notification_update_jira_create_by_state(self) -> None:
        """Test case for i_h_notification__jira_update_create_find_ih_notification_update_jira_create_by_state

        Find Ih Notification Update Jira Create By State
        """
        pass

    def test_i_h_notification__jira_update_create_get_ih_notification_create_by_transaction_id(self) -> None:
        """Test case for i_h_notification__jira_update_create_get_ih_notification_create_by_transaction_id

        Get Ih Notification Create By Transaction Id
        """
        pass

    def test_i_h_notification__jira_update_create_get_ih_notification_update_jira_create(self) -> None:
        """Test case for i_h_notification__jira_update_create_get_ih_notification_update_jira_create

        Get Ih Notification Update Jira Create
        """
        pass

    def test_i_h_notification__jira_update_create_get_ih_notification_update_jira_create_by_id(self) -> None:
        """Test case for i_h_notification__jira_update_create_get_ih_notification_update_jira_create_by_id

        Get Ih Notification Update Jira Create By Id
        """
        pass

    def test_i_h_notification__jira_update_create_increment_ih_notification_update_jira_create_retry_count(self) -> None:
        """Test case for i_h_notification__jira_update_create_increment_ih_notification_update_jira_create_retry_count

        Increment Ih Notification Update Jira Create Retry Count
        """
        pass

    def test_i_h_notification__jira_update_create_update_ih_notification_update_jira_create_state(self) -> None:
        """Test case for i_h_notification__jira_update_create_update_ih_notification_update_jira_create_state

        Update Ih Notification Update Jira Create State
        """
        pass


if __name__ == '__main__':
    unittest.main()
