# coding: utf-8

"""
    sync-service-api-gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sync_service_api_gateway.api.ih_notification_jira_update_close_api import IHNotificationJiraUpdateCloseApi


class TestIHNotificationJiraUpdateCloseApi(unittest.TestCase):
    """IHNotificationJiraUpdateCloseApi unit test stubs"""

    def setUp(self) -> None:
        self.api = IHNotificationJiraUpdateCloseApi()

    def tearDown(self) -> None:
        pass

    def test_i_h_notification__jira_update_close_add_ih_notification_update_jira_close(self) -> None:
        """Test case for i_h_notification__jira_update_close_add_ih_notification_update_jira_close

        Add Ih Notification Update Jira Close
        """
        pass

    def test_i_h_notification__jira_update_close_find_ih_notification_update_jira_close_by_state(self) -> None:
        """Test case for i_h_notification__jira_update_close_find_ih_notification_update_jira_close_by_state

        Find Ih Notification Update Jira Close By State
        """
        pass

    def test_i_h_notification__jira_update_close_get_ih_notification_close_by_transaction_id(self) -> None:
        """Test case for i_h_notification__jira_update_close_get_ih_notification_close_by_transaction_id

        Get Ih Notification Close By Transaction Id
        """
        pass

    def test_i_h_notification__jira_update_close_get_ih_notification_update_jira_close(self) -> None:
        """Test case for i_h_notification__jira_update_close_get_ih_notification_update_jira_close

        Get Ih Notification Update Jira Close
        """
        pass

    def test_i_h_notification__jira_update_close_get_ih_notification_update_jira_close_by_id(self) -> None:
        """Test case for i_h_notification__jira_update_close_get_ih_notification_update_jira_close_by_id

        Get Ih Notification Update Jira Close By Id
        """
        pass

    def test_i_h_notification__jira_update_close_increment_ih_notification_update_jira_close_retry_count(self) -> None:
        """Test case for i_h_notification__jira_update_close_increment_ih_notification_update_jira_close_retry_count

        Increment Ih Notification Update Jira Close Retry Count
        """
        pass

    def test_i_h_notification__jira_update_close_update_ih_notification_update_jira_close_state(self) -> None:
        """Test case for i_h_notification__jira_update_close_update_ih_notification_update_jira_close_state

        Update Ih Notification Update Jira Close State
        """
        pass


if __name__ == '__main__':
    unittest.main()
