# coding: utf-8

"""
    sync-service-api-gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sync_service_api_gateway.models.portal_bp_update import PortalBPUpdate

class TestPortalBPUpdate(unittest.TestCase):
    """PortalBPUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PortalBPUpdate:
        """Test PortalBPUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PortalBPUpdate`
        """
        model = PortalBPUpdate()
        if include_optional:
            return PortalBPUpdate(
                bpnr = '',
                mail = '',
                mail_change = 56,
                mobile = '',
                mobile_change = 56,
                iban = '',
                iban_change = 56,
                datenschutz = '',
                datenschutz_change = 56,
                post = '',
                post_change = 56,
                anmeldeid = '',
                anmeldeid_change = 56,
                change_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                transaction_id = '',
                state = 'initial',
                retry_count = 56,
                creation_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                last_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return PortalBPUpdate(
                bpnr = '',
                mail = '',
                mail_change = 56,
                mobile = '',
                mobile_change = 56,
                iban = '',
                iban_change = 56,
                datenschutz = '',
                datenschutz_change = 56,
                post = '',
                post_change = 56,
                anmeldeid = '',
                anmeldeid_change = 56,
                change_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testPortalBPUpdate(self):
        """Test PortalBPUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
