# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class IHCloseCreate(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'jira_ticket_number': 'object',
        'notif_number': 'object'
    }

    attribute_map = {
        'jira_ticket_number': 'jira_ticket_number',
        'notif_number': 'notif_number'
    }

    def __init__(self, jira_ticket_number=None, notif_number=None):  # noqa: E501
        """IHCloseCreate - a model defined in Swagger"""  # noqa: E501
        self._jira_ticket_number = None
        self._notif_number = None
        self.discriminator = None
        self.jira_ticket_number = jira_ticket_number
        self.notif_number = notif_number

    @property
    def jira_ticket_number(self):
        """Gets the jira_ticket_number of this IHCloseCreate.  # noqa: E501


        :return: The jira_ticket_number of this IHCloseCreate.  # noqa: E501
        :rtype: object
        """
        return self._jira_ticket_number

    @jira_ticket_number.setter
    def jira_ticket_number(self, jira_ticket_number):
        """Sets the jira_ticket_number of this IHCloseCreate.


        :param jira_ticket_number: The jira_ticket_number of this IHCloseCreate.  # noqa: E501
        :type: object
        """
        if jira_ticket_number is None:
            raise ValueError("Invalid value for `jira_ticket_number`, must not be `None`")  # noqa: E501

        self._jira_ticket_number = jira_ticket_number

    @property
    def notif_number(self):
        """Gets the notif_number of this IHCloseCreate.  # noqa: E501


        :return: The notif_number of this IHCloseCreate.  # noqa: E501
        :rtype: object
        """
        return self._notif_number

    @notif_number.setter
    def notif_number(self, notif_number):
        """Sets the notif_number of this IHCloseCreate.


        :param notif_number: The notif_number of this IHCloseCreate.  # noqa: E501
        :type: object
        """
        if notif_number is None:
            raise ValueError("Invalid value for `notif_number`, must not be `None`")  # noqa: E501

        self._notif_number = notif_number

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(IHCloseCreate, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IHCloseCreate):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
