# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class IHClose(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'jira_ticket_number': 'object',
        'notif_number': 'object',
        'transaction_id': 'object',
        'state': 'object',
        'creation_date': 'object',
        'last_updated': 'object'
    }

    attribute_map = {
        'jira_ticket_number': 'jira_ticket_number',
        'notif_number': 'notif_number',
        'transaction_id': 'transaction_id',
        'state': 'state',
        'creation_date': 'creation_date',
        'last_updated': 'last_updated'
    }

    def __init__(self, jira_ticket_number=None, notif_number=None, transaction_id=None, state=None, creation_date=None, last_updated=None):  # noqa: E501
        """IHClose - a model defined in Swagger"""  # noqa: E501
        self._jira_ticket_number = None
        self._notif_number = None
        self._transaction_id = None
        self._state = None
        self._creation_date = None
        self._last_updated = None
        self.discriminator = None
        self.jira_ticket_number = jira_ticket_number
        self.notif_number = notif_number
        if transaction_id is not None:
            self.transaction_id = transaction_id
        if state is not None:
            self.state = state
        if creation_date is not None:
            self.creation_date = creation_date
        if last_updated is not None:
            self.last_updated = last_updated

    @property
    def jira_ticket_number(self):
        """Gets the jira_ticket_number of this IHClose.  # noqa: E501


        :return: The jira_ticket_number of this IHClose.  # noqa: E501
        :rtype: object
        """
        return self._jira_ticket_number

    @jira_ticket_number.setter
    def jira_ticket_number(self, jira_ticket_number):
        """Sets the jira_ticket_number of this IHClose.


        :param jira_ticket_number: The jira_ticket_number of this IHClose.  # noqa: E501
        :type: object
        """
        if jira_ticket_number is None:
            raise ValueError("Invalid value for `jira_ticket_number`, must not be `None`")  # noqa: E501

        self._jira_ticket_number = jira_ticket_number

    @property
    def notif_number(self):
        """Gets the notif_number of this IHClose.  # noqa: E501


        :return: The notif_number of this IHClose.  # noqa: E501
        :rtype: object
        """
        return self._notif_number

    @notif_number.setter
    def notif_number(self, notif_number):
        """Sets the notif_number of this IHClose.


        :param notif_number: The notif_number of this IHClose.  # noqa: E501
        :type: object
        """
        if notif_number is None:
            raise ValueError("Invalid value for `notif_number`, must not be `None`")  # noqa: E501

        self._notif_number = notif_number

    @property
    def transaction_id(self):
        """Gets the transaction_id of this IHClose.  # noqa: E501


        :return: The transaction_id of this IHClose.  # noqa: E501
        :rtype: object
        """
        return self._transaction_id

    @transaction_id.setter
    def transaction_id(self, transaction_id):
        """Sets the transaction_id of this IHClose.


        :param transaction_id: The transaction_id of this IHClose.  # noqa: E501
        :type: object
        """

        self._transaction_id = transaction_id

    @property
    def state(self):
        """Gets the state of this IHClose.  # noqa: E501


        :return: The state of this IHClose.  # noqa: E501
        :rtype: object
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this IHClose.


        :param state: The state of this IHClose.  # noqa: E501
        :type: object
        """

        self._state = state

    @property
    def creation_date(self):
        """Gets the creation_date of this IHClose.  # noqa: E501


        :return: The creation_date of this IHClose.  # noqa: E501
        :rtype: object
        """
        return self._creation_date

    @creation_date.setter
    def creation_date(self, creation_date):
        """Sets the creation_date of this IHClose.


        :param creation_date: The creation_date of this IHClose.  # noqa: E501
        :type: object
        """

        self._creation_date = creation_date

    @property
    def last_updated(self):
        """Gets the last_updated of this IHClose.  # noqa: E501


        :return: The last_updated of this IHClose.  # noqa: E501
        :rtype: object
        """
        return self._last_updated

    @last_updated.setter
    def last_updated(self, last_updated):
        """Sets the last_updated of this IHClose.


        :param last_updated: The last_updated of this IHClose.  # noqa: E501
        :type: object
        """

        self._last_updated = last_updated

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(IHClose, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IHClose):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
